package lexer

var keyword = map[Token]string{
IF:"if",
IN:"in",
DO:"do",
VAR:"var",
FOR:"for",
NEW:"new",
TRY:"try",
GOTO:"goto",
THIS:"this",
ELSE:"else",
CASE:"case",
VOID:"void",
WITH:"with",
NULL:"null",
TRUE:"true",
FALSE:"false",
WHILE:"while",
BREAK:"break",
CATCH:"catch",
THROW:"throw",
RETURN:"return",
TYPEOF:"typeof",
DELETE:"delete",
SWITCH:"switch",
DEFAULT:"default",
FINALLY:"finally",
FUNCTION:"func",
CONTINUE:"continue",
DEBUGGER:"debugger",
INSTANCEOF:"instanceof",
}